# Generated by Django 3.1.13 on 2023-05-11 20:40

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient_name', models.CharField(max_length=50, unique=True)),
                ('image', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/My Projects/AIDE/AIDE_Storage'), upload_to=projects.models.upload_to)),
                ('decription', models.CharField(max_length=5000, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('brain', 'Brain'), ('heart', 'Heart'), ('liver', 'Liver')], default='liver', max_length=50, null=True)),
                ('sample_name', models.CharField(max_length=50)),
                ('input_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:/My Projects/AIDE/AIDE_Storage'), upload_to=projects.models.upload_to)),
                ('iteration_count', models.IntegerField(default=31)),
                ('decription', models.CharField(max_length=5000, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
