# Generated by Django 3.1.13 on 2023-05-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samples',
            name='category',
            field=models.CharField(choices=[('brain', 'Brain'), ('heart', 'Heart'), ('liver', 'Liver')], default='brain', max_length=50, null=True),
        ),
    ]
