# Generated by Django 3.1.13 on 2023-05-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230512_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='samples',
            old_name='decription',
            new_name='description',
        ),
    ]
