# Generated by Django 3.1.13 on 2023-05-13 21:40

import django.core.files.storage
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230512_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\My Projects\\AIDE\\BE Code for AIDE\\aidebe'), upload_to=projects.models.upload_to),
        ),
        migrations.AlterField(
            model_name='samples',
            name='input_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\My Projects\\AIDE\\BE Code for AIDE\\aidebe'), upload_to=projects.models.upload_to),
        ),
    ]
