# Generated by Django 3.1.13 on 2023-06-10 16:29

import django.core.files.storage
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230514_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ubuntu/mystorage'), upload_to=projects.models.upload_to),
        ),
        migrations.AlterField(
            model_name='samples',
            name='input_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ubuntu/mystorage'), upload_to=projects.models.upload_to_path),
        ),
    ]
